version: '3'

services:
  sonnen_exporter:
    container_name: sonnen_exporter
    image: prometheuscommunity/json-exporter:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./json_exporter_config.yml:/config.yml
    command:
      - '--config.file=/config.yml'
    ports:
      - '7979:7979'
