---
- name: Create /opt/sonnen_exporter
  file:
    path: '{{ sonnen_exporter_path }}'
    state: directory
    owner: root
    group: root
    mode: 0775
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ sonnen_exporter_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy json_exporter_config.yml
  ansible.builtin.template:
    src: json_exporter_config.yml.j2
    dest: '{{ sonnen_exporter_path }}/json_exporter_config.yml'
    owner: root
    group: root
    mode: 0664
